heavy upgrades on tig install and tig login, moved tig dir to ~/.tig

diff --git a/bin/tig-install b/bin/tig-install
--- a/bin/tig-install
+++ b/bin/tig-install
@@ -2,7 +2,10 @@
 #
 # This script installs required applications
 
-TIGRC_PATH="$HOME/.tigrc"
+set -e
+
+TIG_ROOT="${TIG_HOME-"$HOME/.tig"}"
+TIGRC_PATH="$TIG_ROOT/.tigrc"
 if [ ! -f "$TIGRC_PATH" ] ; then
   src_root="$HOME/src"
   if [ ! -d "$src_root/cchamberlain/tig" ] ; then
@@ -13,111 +16,148 @@ if [ ! -f "$TIGRC_PATH" ] ; then
   fi
   cp "$src_root/cchamberlain/tig/lib/tigrc" "$TIGRC_PATH"
 fi
-
 . "$TIGRC_PATH"
 
->&2 echo "--Installing Required Applications--"
-if ! hash rimraf 2>/dev/null; then
-  >&2 echo "--Installing rimraf--"
-  >&2 echo "--**short for 'rm -rf' (remove recursive/force)**--"
-  npm install -g rimraf >/dev/null
+required_flag=false
+optional_flag=false
+
+usage_short="${BLUE}usage: tig install [-r] [-o]"
+usage_long="$usage_short\n-r: install required components (default: $required_flag).${NC}"
+usage_long="$usage_long\n-o: install optional components (default: $optional_flag).${NC}"
+
+usage_short="$usage_short\nUse -h to get supported command information.${NC}"
+
+options=":roh"
+shopt -u nocasematch
+OPTIND=1
+while getopts "$options" opt ; do
+    case "$opt" in
+    r )
+      required_flag=true
+      ;;
+    o )
+      optional_flag=true
+      ;;
+    h )
+      >&2 echo -e "$usage_long" && exit 1
+      exit 0
+      ;;
+    \?)
+      >&2 echo -e "Unknown option: -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    : )
+      >&2 echo -e "Missing option argument for -$OPTARG"
+      >&2 echo -e "$usage_short"
+      exit 1
+      ;;
+    * )
+      >&2 echo -e "Unimplemented option: -$OPTARG" && exit 1
+      >&2 echo -e "$usage_short"
+      exit 1
+    esac
+done
+shift $((OPTIND-1))
+
+
+if [ "$required_flag" = true ] ; then
+
+  if ! hash rimraf 2>/dev/null; then
+    >&2 echo -e "${CYAN}- installing rimraf... -${NC}"
+    npm install -g rimraf >/dev/null
+    >&2 echo -e "${GREEN}- installing rimraf... -${NC}"
+  fi
+
+  if ! hash mkdirp 2>/dev/null; then
+    >&2 echo -e "${CYAN}- installing mkdirp... -${NC}"
+    npm install -g mkdirp >/dev/null
+    >&2 echo -e "${GREEN}- mkdirp installed successfully -${NC}"
+  fi
+
+  if ! hash jq 2>/dev/null; then
+    >&2 echo -e "${CYAN}- installing jq... -${NC}"
+    if [ "$PNAME" = "windows" ]; then
+      curl http://stedolan.github.io/jq/download/win64/jq.exe >"${LOCAL_BIN_ROOT}/jq.exe"
+    elif ! hash brew 2>/dev/null; then
+      brew install jq
+    else
+      curl http://stedolan.github.io/jq/download/linux64/jq >"${LOCAL_BIN_ROOT}/jq"
+    fi
+    >&2 echo -e "${GREEN}- jq installed successfully -${NC}"
+  fi
+
+  if ! hash chrome 2>/dev/null; then
+    if [ "$PNAME" = "windows" ]; then
+      >&2 echo -e "${CYAN}- installing chrome... -${NC}"
+      cinst google-chrome-x64 -yf
+      >&2 echo -e "${GREEN}- chrome installed successfully -${NC}"
+    fi
+  fi
+
 fi
-if ! hash mkdirp 2>/dev/null; then
-  >&2 echo "--Installing mkdirp--"
-  >&2 echo "--**short for 'mkdir -p' (make directory recursively and skip silently if directory exists)**--"
-  npm install -g mkdirp >/dev/null
-fi
-if ! hash jq 2>/dev/null; then
-  >&2 echo "--Installing jq--"
-  >&2 echo "--**makes working with json on the command line easier**--"
+
+
+if [ "$optional_flag" = true ] ; then
+
+  if ! hash atom 2>/dev/null; then
+    if [ "$PNAME" = "windows" ] ; then
+      >&2 echo -e "${CYAN}- installing atom... -${NC}"
+      cinst Atom -yf
+      >&2 echo -e "${GREEN}- atom installed successfully -${NC}"
+    fi
+  fi
+
+  if ! hash ack 2>/dev/null; then
+    >&2 echo -e "${CYAN}- installing ack... -${NC}"
+    curl http://beyondgrep.com/ack-2.14-single-file > "${LOCAL_BIN_ROOT}/ack"
+    >&2 echo -e "${GREEN}- ack installed successfully -${NC}"
+  fi
+
+  if ! hash nodemon 2>/dev/null; then
+    >&2 echo -e "${CYAN}- installing nodemon... -${NC}"
+    npm install -g nodemon >/dev/null
+    >&2 echo -e "${GREEN}- nodemon installed successfully -${NC}"
+  fi
+
+  if ! hash forever 2>/dev/null; then
+    >&2 echo -e "${CYAN}- installing forever... -${NC}"
+    npm install -g forever >/dev/null
+    >&2 echo -e "${GREEN}- forever installed successfully -${NC}"
+  fi
+
+  if ! hash ag 2>/dev/null; then
+    >&2 echo -e "${CYAN}- Installing ag (the silver searcher)... -${NC}"
+    if hash brew 2>/dev/null; then
+      brew install the_silver_searcher
+      >&2 echo -e "${GREEN}- ag installed successfully -${NC}"
+    elif hash pacman 2>/dev/null; then
+      pacman -S the_silver_searcher
+      >&2 echo -e "${GREEN}- ag installed successfully -${NC}"
+    elif hash choco 2>/dev/null; then
+      cinst ag -yf &>/dev/null
+      >&2 echo -e "${GREEN}- ag installed successfully -${NC}"
+    fi
+  fi
+
   if [ "$PNAME" = "windows" ]; then
-    curl http://stedolan.github.io/jq/download/win64/jq.exe >"${LOCAL_BIN_ROOT}/jq.exe"
-  elif ! hash brew 2>/dev/null; then
-    brew install jq
-  else
-    curl http://stedolan.github.io/jq/download/linux64/jq >"${LOCAL_BIN_ROOT}/jq"
-  fi
-fi
-if ! hash chrome 2>/dev/null; then
-  >&2 echo "--Installing chrome--"
-  if [ "$PNAME" = "windows" ]; then
-    choco install google-chrome-x64
-  fi
-fi
+    ### sysinternals: process explorer
+    if ! hash procmon 2>/dev/null ; then
+      >&2 echo -e "${CYAN}- installing sysinternals... -${NC}"
+      cinst sysinternals -yf
+      >&2 echo -e "${GREEN}- sysinternals installed successfully -${NC}"
+    fi
 
-
-
-#TODO: Put -o flag here
-echo "--Installing optional packages--"
-
-if ! hash ack 2>/dev/null; then
-  ### ack: Fast file searching
-  echo "Installing ack..."
-  curl http://beyondgrep.com/ack-2.14-single-file > "${LOCAL_BIN_ROOT}/ack"
-  echo "ack installed successfully."
-fi
-
-if ! hash nodemon 2>/dev/null; then
-  >&2 echo "--Installing nodemon--"
-  >&2 echo "--**runs node.js and watches server-side files for updates to trigger process reload**--"
-  npm install -g nodemon >/dev/null
-fi
-
-if ! hash forever 2>/dev/null; then
-  >&2 echo "--Installing forever--"
-  >&2 echo "--**runs node.js in a production setting, ensuring the process never goes down**--"
-  npm install -g forever >/dev/null
-fi
-
-if ! hash gulp 2>/dev/null; then
-  >&2 echo "--Installing gulp--"
-  npm install -g gulp >/dev/null
-fi
-
-if ! hash ag 2>/dev/null; then
-  >&2 echo "--Installing ag (the silver searcher)--"
-  if hash brew 2>/dev/null; then
-    brew install the_silver_searcher
-  elif hash pacman 2>/dev/null; then
-    pacman -S the_silver_searcher
-  elif hash choco 2>/dev/null; then
-    choco install ag --yes --force &>/dev/null
-  fi
-fi
-
-
-if [ "$PNAME" = "windows" ]; then
-  ### sysinternals: process explorer
-  ### Good for looking at windows processes, file locking, etc.
-  if ! hash procexp 2>/dev/null; then
-    >&2 echo "--Installing procexp--"
-    procexp_url="https://download.sysinternals.com/files/ProcessExplorer.zip"
-    procexp_path="${LOCAL_BIN_ROOT}/procexp.exe"
-    mkdir -p "$SRC_ZIP_ROOT"
-    pushd "$SRC_ZIP_ROOT"
-      curl -L $procexp_url >ProcessExplorer.zip
-      unzip -po ProcessExplorer.zip procexp.exe >$procexp_path
-    popd
+    if ! hash mongod 2>/dev/null; then
+      >&2 echo -e "${CYAN}- installing mongodb... -${NC}"
+      mkdirp "${SRC_BIN_ROOT}"
+      pushd "${SRC_BIN_ROOT}"
+        curl -L https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.0.3-signed.msi >mongodb_x86_64.msi
+        cmd //c msiexec.exe //q //i mongodb-3.0.3-signed.msi INSTALLLOCATION="%USERPROFILE%\\local\\mongodb"
+        mkdirp "${TIG_ROOT}/data/db"
+      popd
+      >&2 echo -e "${GREEN}- mongodb installed successfully -${NC}"
+    fi
   fi
 
-  if ! hash procmon 2>/dev/null; then
-    >&2 echo "--Installing procmon--"
-    procmon_url="https://download.sysinternals.com/files/ProcessMonitor.zip"
-    procmon_path="${LOCAL_BIN_ROOT}/procmon.exe"
-    mkdir -p "$SRC_BIN_ROOT"
-    pushd "$SRC_BIN_ROOT"
-      curl -L $procmon_url >ProcessMonitor.zip
-      unzip -po ProcessMonitor.zip Procmon.exe >$procmon_path
-    popd
-  fi
-
-  if ! hash mongod 2>/dev/null; then
-    >&2 echo "--Installing mongod--"
-    mkdirp "${SRC_BIN_ROOT}"
-    pushd "${SRC_BIN_ROOT}"
-      curl -L https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.0.3-signed.msi >mongodb_x86_64.msi
-      cmd //c msiexec.exe //q //i mongodb-3.0.3-signed.msi INSTALLLOCATION="%USERPROFILE%\\local\\mongodb"
-      mkdirp "${TIG_ROOT}/data/db"
-    popd
-  fi
 fi
diff --git a/bin/tig-login b/bin/tig-login
--- a/bin/tig-login
+++ b/bin/tig-login
@@ -1,37 +1,41 @@
 #!/bin/bash
 #
-# tig-login [-n] [-a] [-t] username|organization
+# usage: tig login [-u username[:password]] [-t token] [-s url]
 # Authorize with tig and cloud providers
 
 set -e
 
-TIGRC_PATH="$HOME/.tigrc"
-if [ ! -f "$TIGRC_PATH" ] ; then
-  src_root="$HOME/src"
-  if [ ! -d "$src_root/cchamberlain/tig" ] ; then
-    mkdir -p "$src_root/cchamberlain"
-    pushd "$src_root/cchamberlain"
-      git clone https://github.com/cchamberlain/tig
-    popd
-  fi
-  cp "$src_root/cchamberlain/tig/lib/tigrc" "$TIGRC_PATH"
-fi
+TIG_ROOT="${TIG_HOME-"$HOME/.tig"}"
+TIGRC_PATH="$TIG_ROOT/.tigrc"
 . "$TIGRC_PATH"
 
-renew=false
+auth_type=""
+user_string=""
+token=""
+tig_link_url="http://tig.link"
 
-usage_short="${CYAN}Usage: tig-login [-r]"
-usage_long="$usage_short\n-r: Get a fresh token from GitHub."
+usage_short="${BLUE}usage: tig login [-u username[:password]] [-t token] [-s url]"
+usage_long="$usage_short\n-u: use basic auth to (re)authorize with github/tig api"
+usage_long="$usage_long\n-t: use bearer token authentication to (re)authorize with tig api"
+usage_long="$usage_long\n-s: override the tig link url (default: $tig_link_url)${NC}"
 
-usage_short="$usage_short\nUse -h to get supported command information."
+usage_short="$usage_short\nuse -h to get supported command information${NC}"
 
-options=":rh"
+options=":u:t:s:h"
 shopt -u nocasematch
 OPTIND=1
 while getopts "$options" opt ; do
     case "$opt" in
-    r ) # Gets latest annotated revision
-      renew=true
+    u )
+      auth_type="basic"
+      user_string="$OPTARG"
+      ;;
+    t )
+      auth_type="bearer"
+      token="$OPTARG"
+      ;;
+    s )
+      tig_link_url="$OPTARG"
       ;;
     h )
       >&2 echo -e "$usage_long" && exit 1
@@ -55,7 +59,6 @@ while getopts "$options" opt ; do
 done
 shift $((OPTIND-1))
 
-readonly GITHUB_TOKEN_KEY="GITHUB_TOKEN"
 
 ### --GIT CONFIG--
 ### Setup global git configuration if not set.
@@ -64,35 +67,89 @@ GIT_CONFIG_PATH="$HOME/.gitconfig"
 if [ ! -f "$GIT_CONFIG_PATH" ]; then
   >&2 touch "$GIT_CONFIG_PATH"
   >&2 clear
-  >&2 echo "--First time git setup--"
-  >&2 echo "--You will be prompted for information regarding your global git configuration--"
+  >&2 echo -e "${CYAN}- setting global git defaults... -${NC}"
 fi
+
+
+user_full_name=""
+user_email=""
 
 git_config=$(git config --global -l)
 
 if ! grep -q user.name <<< "$git_config" ; then
-  >&2 echo "--No user name set in git global configuration--"
-  >&2 echo -n "Your full name (e.g. 'John Doe'): "
-  read git_user
-  >&2 git config --global user.name "$git_user"
-fi
-if ! grep -q user.email <<< "$git_config" ; then
-  >&2 echo "--No user email set in git global configuration--"
-  >&2 echo -n "Your email address: "
-  read git_email
-  >&2 git config --global user.email "$git_email"
-fi
-if ! grep -q credential.helper <<< "$git_config" ; then
-  >&2 echo "--Git credential helper not configured, configuring now--"
-  >&2 git config --global credential.helper wincred
-fi
-if ! grep -q push.default <<< "$git_config" ; then
-  >&2 echo "--Git push default not set, configuring to simple--"
-  >&2 git config --global push.default simple
+  >&2 echo -e "${CYAN}- configuring git friendly user name... -${NC}"
+  while [ "$user_full_name" = "" ] ; do
+    >&2 echo -n "what is your full name (e.g. 'John Doe')? "
+    read user_full_name
+    if [ "$user_full_name" = "" ] ; then
+      >&2 echo -e "${RED}- that doesn't appear to be a name! try again... -${NC}"
+    fi
+  done
+  >&2 git config --global user.name "$user_full_name"
+  >&2 echo -e "${GREEN}- git friendly user name configured as $user_full_name -${NC}"
+else
+  user_full_name="$(git config --get --global user.name)"
 fi
 
-### If config file does not exist or does not contain the github token
-if [ "$renew" = true ] || [ ! -e "$TIGRC_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY "$TIGRC_PATH"; then
+if ! grep -q user.email <<< "$git_config" ; then
+  >&2 echo -e "${CYAN}- configuring git email address... -${NC}"
+  while [ "$user_email" = "" ] ; do
+    >&2 echo -n "what is your email? "
+    read user_email
+    if [ "$user_email" = "" ] ; then
+      >&2 echo -e "${RED}- that doesn't appear to be an email address! try again... -${NC}"
+    fi
+  done
+  >&2 git config --global user.email "$user_email"
+  >&2 echo -e "${GREEN}- git email address configured as $user_email -${NC}"
+else
+  user_email="$(git config --get --global user.email)"
+fi
+
+
+if ! grep -q credential.helper <<< "$git_config" ; then
+  if [ "$PNAME" = "windows" ] ; then
+    >&2 echo -e "${CYAN}- configuring git credential helper... -${NC}"
+    >&2 git config --global credential.helper wincred
+    >&2 echo -e "${GREEN}- credential helper configured successfully -${NC}"
+  fi
+fi
+
+if ! grep -q push.default <<< "$git_config" ; then
+  >&2 echo -e "${CYAN}- configuring default git push behavior to simple... -${NC}"
+  >&2 git config --global push.default simple
+  >&2 echo -e "${GREEN}- git default push behavior configured successfully -${NC}"
+fi
+
+
+if [ "$auth_type" = "basic" ] ; then
+  username="$(echo "$user_string" | sed 's/[: ][\w[:punct:] ]+//')"
+  password="$(echo "$user_string" | sed 's/[\w[:punct:] ]+://')"
+
+  while [ "$password" = "" ] ; do
+    >&2 echo -n "enter your github password: "
+    read -s password
+    if [ "$password" = "" ] ; then
+      >&2 echo -e "${RED}- that doesn't appear to be a valid password! try again... -${NC}"
+    fi
+  done
+
+  tig_data="{\"full_name\":\"$user_full_name\",\"email\":\"$user_email\",\"hostname\":\"$(hostname)\",\"hostuser\":\"$(id -un)\",\"platform\":\"$PLATFORM\"}"
+
+  tig_credentials="$username:$password"
+
+  tig_response=$(curl -s -u ${tig_credentials} -X POST -d "$tig_data" "$tig_link_url") 2>&1
+  echo "$tig_response"
+elif [ "$auth_type" = "bearer" ] ; then
+  bearer_token_header="Authorization: Bearer $token"
+  tig_response="$(curl -s -H "$bearer_token_header" -X POST "$tig_link_url")" 2>&1
+  echo "$tig_response"
+else
+  >&2 echo "${RED}- must pass -u or -t flag... -${NC}"
+  exit 1
+fi
+
+if [ "$renew" = true ] ; then
     >&2 echo "--GitHub credentials are required to interact with the GitHub api--"
     >&2 echo "--Your basic credentials will be exchanged for a token and persisted to ${TIGRC_PATH}--"
 
@@ -128,7 +185,7 @@ if [ "$renew" = true ] || [ ! -e "$TIGRC_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY 
             >&2 echo "--Token has already been granted for you but was lost.  Login to window at the right, revoke token named \"$oauth_note\", and close the window--"
             chrome_path="unknown"
             token_url="https://github.com/settings/tokens"
-            >&2 chrome-box "$token_url"
+            >&2 chrome "$token_url"
             ;;
           *Bad\ credentials*) ### Wrong username/password provided
             >&2 echo "--The username / password combination you provided was incorrect.  Try again--"
@@ -146,7 +203,7 @@ if [ "$renew" = true ] || [ ! -e "$TIGRC_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY 
         do
          if [ ${#token} -eq 40 ]; then
             ### Set the github token in the config
-            echo -e "\r\nexport $GITHUB_TOKEN_KEY=\"$token\"\r\n" >>$TIGRC_PATH
+            echo -e "\r\nexport GITHUB_TOKEN=\"$token\"\r\n" >>$TIGRC_PATH
             GITHUB_AUTH_HEADER="Authorization: token $token"
             echo -e "\r\nexport GITHUB_AUTH_HEADER=\"$GITHUB_AUTH_HEADER\"\r\n" >>$TIGRC_PATH
             ### Replace github url with token github url in config
@@ -175,13 +232,13 @@ if [ "$renew" = true ] || [ ! -e "$TIGRC_PATH" ] || ! grep -q $GITHUB_TOKEN_KEY 
 fi
 
 ### Source the variable from the config file
-. "$TIGRC_PATH"
+#. "$TIGRC_PATH"
 
-if [ -n "$GITHUB_TOKEN" ]; then
+#if [ -n "$GITHUB_TOKEN" ]; then
     ### Update all github tokens
-    echo "$GITHUB_TOKEN" | tr -d '\n'
-    exit 0
-else
-    >&2 echo "--$GITHUB_TOKEN_KEY not found in the config file! Exiting...--"
-    exit 1
-fi
+    #echo "$GITHUB_TOKEN" | tr -d '\n'
+    #exit 0
+#else
+    #>&2 echo "--GITHUB_TOKEN not found in the config file! Exiting...--"
+    #exit 1
+#fi
